apiVersion: apps/v1
kind: Deployment
metadata:
  name: atplcrm-web
  namespace: atplcrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atplcrm-web
  template:
    metadata:
      labels:
        app: atplcrm-web
    spec:
      containers:
        - name: web
          image: chinninaidu/atplcrm-web:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: atplcrm-web
  namespace: atplcrm
spec:
  selector:
    app: atplcrm-web
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
